# fileName: api_config.yml

host: https://XXX

unlogin_otc_list:
  name: 未登录法币列表接口
  method: Get
  url: /otc/coin/list
  data:
  headers:

login_sandbox_email:
  name: 【登录】邮箱登录
  method: Post
  url: /v1/login/
  data:
    phone_country:
    phone_number:
    email: 1@qq.com
    password: 1
    device_id:
    device_name: Iphone8plus
    device_pubkey:
  headers:
    Content-Type: application/x-www-form-urlencoded
    Authorization: Basic

asset_main:
  name: 【资产】用户资产列表页
  method: Get
  url: /v2/assets/main/
  headers:
    Authorization: Bearer
    app-version: 4.8.0
    device-id: FE6C89E6-1B18-43C3-B9B9-CA2D773D64D8
  expected:
    success: true

